#!/bin/sh
mkdir /nfs_scratch/ojalvo/LTau_Feb15
cd /nfs_scratch/ojalvo/LTau_Feb15
W=1;Z=0;TOP=0;VV=0;


#nohup mergeFiles   --copy-timeout=90 W1JETS_2.root /hdfs/store/user/$USER/W1Jets_2-SUB-MCW &
#nohup mergeFiles  --copy-timeout=90 TT_LL.root /hdfs/store/user/$USER/TTBar_LL-SUB-MC 
#nohup mergeFiles  --copy-timeout=90 TT_HL.root /hdfs/store/user/$USER/TTBar_HL-SUB-MC 
#nohup mergeFiles  --copy-timeout=90 TT_HH.root /hdfs/store/user/$USER/TTBar_HH-SUB-MC 

#cp /nfs_scratch/ojalvo/LTau_Feb15/W1JETS_2.root /nfs_scratch/ojalvo/unweighted/.
#cp /nfs_scratch/ojalvo/LTau_Feb15/TT_LL.root /nfs_scratch/ojalvo/unweighted/.
#cp /nfs_scratch/ojalvo/LTau_Feb15/TT_HL.root /nfs_scratch/ojalvo/unweighted/.
#cp /nfs_scratch/ojalvo/LTau_Feb15/TT_HH.root /nfs_scratch/ojalvo/unweighted/.


#if [ -e W_1.root ] && [ -e W_2.root ] && [ $W -eq 1 ]
#    then
#    hadd W.root W_1.root W_2.root
#    hadd  W2JETS.root W2JETS_1.root W2JETS_2.root
#    hadd  W3JETS.root W3JETS_1.root W3JETS_2.root
#else
#    echo " Error in WJETS merging " > logMerge
#fi

if [ $Z -eq 1 ]
    then
    EventWeightsIterativeZJets   doOneD=1   weight=3504   type=3 histoName='MT/results'
    #EventWeightsIterative outputFile='ZJETS.root'   doOneD=1   weight=3504   type=3 histoName='MT/results'
    hadd  ZJETS.root Z.root Z1JETS.root Z2JETS.root Z3JETS.root Z4JETS.root
    EventWeightsForEfficiencyFast $1 outputFile='ZJETS.root' 
    EventWeightsForEfficiencyZEE $1 outputFile='ZJETS.root' 
else
    echo " Error in ZJETS merging " >> logMerge
fi

if [ -e W1JETS_1.root ] && [ -e W2JETS_1.root  ] && [ -e W3JETS_1.root  ] && [ -e W4JETS.root  ] && [ $W -eq 1 ] && [ -e W1JETS_2.root ] && [ -e W2JETS_2.root  ] && [ -e W3JETS_2.root  ]
    then
    hadd W.root W_1.root W_2.root		  
    hadd  W2JETS.root W2JETS_1.root W2JETS_2.root
    hadd  W3JETS.root W3JETS_1.root W3JETS_2.root    
    EventWeightsIterativeWJets       doOneD=1   weight=36257   type=4 histoName='MT/results'
    hadd WJETS.root W.root W1JETS.root W2JETS.root W3JETS.root W4JETS.root
    EventWeightsForEfficiencyFastWJets $1 outputFile='WJETS.root'
else
    echo " Error in W merging " >> logMerge
fi

#if [ -e TOP.root ] && [ -e TT_LL.root ] && [ -e TT_HH.root ] && [ -e TT_HL.root ] && [ $TOP -eq 1 ]
if [ -e TT_LL.root ] && [ -e TT_HH.root ] && [ -e TT_HL.root ] && [ $TOP -eq 1 ]
    then
    #EventWeightsIterative outputFile='TOP.root'      doOneD=1   weight=225.2    type=6 histoName='MT/results'
    EventWeightsIterative outputFile='TT_LL.root'      doOneD=1   weight=26.2    type=6 histoName='MT/results'
    EventWeightsIterative outputFile='TT_HH.root'      doOneD=1   weight=114    type=6 histoName='MT/results'
    EventWeightsIterative outputFile='TT_HL.root'      doOneD=1   weight=109.3    type=6 histoName='MT/results'
    hadd  TT_LL.root TT_HH.root TT_HL.root 
    #EventWeightsForEfficiencyFast $1 outputFile='TOP.root'
else
    echo " Error in TOP merging " >> logMerge
fi

if [ -e WW-2L.root ] && [ -e WZ-3L.root ] && [ -e ZZ-4L.root ] && [ -e WZ-LLQQ.root ] && [ -e ZZ-LLQQ.root ] && [ -e tW.root ] && [ -e tBarW.root ] && [ $VV -eq 1 ]
    then
    EventWeightsIterative outputFile='WW-2L.root'   doOneD=1   weight=5.824    type=7 histoName='MT/results'
    EventWeightsIterative outputFile='WZ-3L.root'   doOneD=1   weight=1.058   type=7 histoName='MT/results'
    EventWeightsIterative outputFile='ZZ-4L.root'   doOneD=1   weight=0.181    type=7  histoName='MT/results'
#EventWeightsIterative outputFile='ZZ-LLVV.root' doOneD=1   weight=0.716    type=7  histoName='MT/results'
    EventWeightsIterative outputFile='WZ-LLQQ.root' doOneD=1   weight=2.207    type=7 histoName='MT/results' 
    EventWeightsIterative outputFile='ZZ-LLQQ.root' doOneD=1   weight=2.502    type=7 histoName='MT/results'
    EventWeightsIterative outputFile='tW.root'  	doOneD=1   weight=11.1    type=6 histoName='MT/results' 
    EventWeightsIterative outputFile='tBarW.root'  	doOneD=1   weight=11.1    type=6 histoName='MT/results' 
    hadd VV.root WW-2L.root WZ-3L.root  ZZ-LLQQ.root WZ-LLQQ.root tW.root tBarW.root ZZ-4L.root ZZ-LLQQ.root
    EventWeightsForEfficiencyFast $1 outputFile='VV.root'
else
    echo " Error in VV region " >> logMerge
fi

#rm W.root W1JETS.root W2JETS.root W3JETS.root W4JETS.root 
#rm WW-2L.root WZ-3L.root ZZ-4L.root ZZ-LLQQ.root WZ-LLQQ.root tW.root tBarW.root













